openapi: 3.0.1
info:
  title: Sample API
  description: API description in Markdown.
  version: 1.0.0
servers:
  - url: 'http://localhost:8080'
components:
  schemas:
    Message:
      type: object
      properties:
        content:
          type: String
          description: message payload
        identifier:
          type: string
          description: message identifier for rate limiting

paths:
  /push-to-queue:
    post:
      summary: Push message to queue
      description: Optional extended description in Markdown.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Message'
      responses:
        '200':
          description: OK
